### ISSUE TITLE
How Do I enable these??

### ISSUE THREAD

**Issue by Kenfin777** [Zikoat/minesweeper#1]

**Comment by Zikoat** [comment]
Yeah, it is pretty hard to run some of these 😅.  
"first" you can just run the .bat file on windows. 

[infinite try 3](https://github.com/Zikoat/minesweeper/tree/master/infinite%20try%203), [infinite website](https://github.com/Zikoat/minesweeper/tree/master/infinite%20website), [my website](https://github.com/Zikoat/minesweeper/tree/master/my%20website), [myWebsite2](https://github.com/Zikoat/minesweeper/tree/master/myWebsite2), [percolation](https://github.com/Zikoat/minesweeper/tree/master/percolation) you have to run `npx http-server` in the main directory, then open the individual html files in your browser through the web server (i think... Some of these havent been opened since 2015).

[insanity sweeper](https://github.com/Zikoat/minesweeper/tree/master/insanity%20sweeper), you have to run with java.

[minesweeperPerlin](https://github.com/Zikoat/minesweeper/tree/master/minesweeperPerlin) has to be opened in [processing](https://processing.org/)

If you wanna know how to run some of these specifically you can ask, if not then im gonna close this.
